hoaxdetector/urls.py
from django.conf.urls import url
from .views import index, main

urlpatterns = [
    # index
    url(r'^$', index, name='index'),
    url(r'^main/$', main, name='main')
]

hoaxrecognizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import hoaxdetector.urls as hoax
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hoax/', include(hoax,namespace='hoax')),
    url(r'^$', RedirectView.as_view(url = "/hoax/", permanent = "true"), name = 'index'),
]

hoaxdetector/models.py
from django.db import models

# Create your models here.

hoaxdetector/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
import string
from joblib import load

# Create your views here.
# Ini adalah method untuk merender halaman utama
def index(request):
	response = {}
	html = 'hoaxdetect/hoaxdetect.html'
	return render(request, html, response)

# Method untuk menerima input dari pengguna dan mengolah input tersebut dengan metode naive bayes classifier, pos tagging, dibuang 
# stopwordsnya, stemming dan juga mengembalikan output dalam bentuk JSON untuk ditampilkan di front end
@csrf_exempt
def main(request):
	if request.method == 'POST':
		inputan = request.POST['paramm']
		stringBenar = inputan.lower().split(" ")
		temp = []
		file = open("hoaxdetector/stopwords.txt")
		data = file.read().splitlines()                      # Membuka file berisi kumpulan stopwords dan menyimpannya ke dalam array
		file.close()
		hasilInputSudahDistem = []
		hasilInputDiClean = []
		for i in stringBenar:
			i = i.strip(string.punctuation)                   # Membuang tanda baca pada inputan dari pengguna
			kata = stemmer(i)                                 # Melakukan metode stemming pada inputan dari user
			hasilInputDiClean.append(kata)
			if kata not in data:                             # Kondisi untuk menghilangkan stopwords
				hasilInputSudahDistem.append(kata)
		pos_tag =  retrieve_post_tag(" ".join(hasilInputDiClean))                   # Memanggilan fungsi pos tagging terhadap inputan dari pengguna
	                                                                                # yang sudah dibersihkan dari tanda baca, imbuhan, dan stopwords
		result = processInput(" ".join(hasilInputSudahDistem) + " %s" % (pos_tag))
		res = {"hasil":"Probabilitas berita ini hoax adalah %d persen"% (int(result * 100))}
		return JsonResponse(res)

# Ini adalah method untuk mencari nilai tdidf dan juga probabilitas hoax dari inputan yang diberikan pada parameter dengan memakai 
# metode Naive Bayes Classfier, bila ingin dilihat lebih rinci untuk metode kalkulasi probabilitasnya, dapat menjalankan file tfidf.joblib 
# dan bayes.joblib pada jupyter (Apabila ingin melihat kode untuk melakukan kalkulasi tersebut)
def processInput(inputBersih):
	vectorizer = load("hoaxdetector/tfidf.joblib")
	bayes = load("hoaxdetector/bayes.joblib")
	vector = vectorizer.transform([inputBersih])
	prediction = bayes.predict_proba(vector)
	return prediction[0][1]

# Method untuk melakukan pos tagging terhadap input yang diberikan dengan memakai web service dari Fasilkom UI
def retrieve_post_tag(inputBersih):
	url = 'http://fws.cs.ui.ac.id/SampleClientPOSTag/SampleCLient'
	data = {'submit':'Get POS', 'inputWord' : inputBersih}
	try:
		r = requests.post(url, data = data, timeout= 3)
		soup = BeautifulSoup(r.text, 'html.parser')
		all_pos = soup.find_all('postag')
		pos_list = [J.text for J in all_pos]
		enamurated_pos = []
		for I in range(len(pos_list)):
			enumerated_pos.append("%d%s" % (I, pos_list[I]))
		return " ".join(enumerated_pos)
	except:
		return ""

# Fungsi untuk melakukan stemmer
def stemmer(kata):
	temp = stemmerPre(kata)
	temp1 = stemmerPre(temp)
	temp2 = stemmerPre(temp1)
	temp3 = stemmerSuf(temp2)
	temp4 = stemmerSuf(temp3)
	return temp4

# Fungsi untuk melakukan stemming pada imbuhan di depan seperti (di-, ke-, se-, me-,mem-,pem-,peng-,peny-,meng-,meny-, kem-, diper-,memper-
# ,kem-,memak- (untuk kasus kata memakan))
def stemmerPre(kata):
	if (len(kata) > 5):
		arrImbuhan2 = ["di","ke","se"]
		arrImbuhanSpec = ["me","pe"]
		vocal = ["a","i","u","e","o"]
		prefix = kata[:2]
		if(prefix in arrImbuhan2):
			if(kata[:5] == "diper"):
				return kata[5:]
			elif(kata[:3] == "kem"):
				return kata
			else:
				return kata[2:]
		elif(kata[:6] == "memper"):
			return kata[6:]
		elif(kata[:2] in arrImbuhanSpec and kata[2:4] == "ng" and kata[4] in vocal):
			return "k"+kata[4:]
		elif(kata[:2] in arrImbuhanSpec and kata[2:4] == "ny" and kata[4] in vocal):
			return "s"+kata[4:]
		elif(kata[:2] == "be" and kata[2] == "r" and kata[3] == "e" and kata[4] == "t"):
			return kata[3:]
		elif(kata[:2] == "be" and kata[2] == "r" and kata[3] == "e"):
			return kata[2:]
		elif(kata[:2] == "be" and kata[2] == "r" and kata[3] != "e"):
			return kata[3:]
		else:
			if(prefix in arrImbuhanSpec):
				char = kata[2]
				if(char == "m"):
					if(kata[:5] == "memak"):
						return kata[2:]
					else:
						return "p"+kata[3:]
				elif(char == "n"):
					return "t"+kata[3:]
	return kata

# Method untuk melakukan stemming terhadap imbuhan belakang seperti (-kan, -lah, -nya, -kah, -an, -i)
def stemmerSuf(kata):
	if(len(kata) > 5):
		arrImbuhanBlkg = ["kan","lah","nya","kah"]
		suffix = kata[-3:]
		if(suffix in arrImbuhanBlkg):
			return kata[:-3]
		elif(kata[-2:] == "an"):
			return kata[:-2]
		elif(kata[-1] == "i"):
			return kata[:-1]
	return kata

hoaxdetector/templates/hoaxdetect/hoaxdetect.html
{% extends "hoaxdetect/layout/base.html" %}
{% block content %}
<h1 style="text-align:center;color: darkblue;font-family:Verdana">
Selamat datang di Hoax Detector</h1>
<h3 style = "text-align: center; color:darkblue;font-style:Verdana">Dengan Akurasi sebesar 79%</h3>
<br>
<textarea id="temp" style="resize:none;width:500px;height:500px;font-size:18px;
	margin-left:100px;" placeholder = "Masukkan input berita disini..."></textarea>
<input id = "but" type="submit" class="btn btn-success" value="Proses" 
	style="margin-left:30px;margin-top:-950px">
</input>
<textarea placeholder = "Ini adalah kotak output hasil olahan berita yang diberikan" id = "res" 
style="resize:none;width:500px;height:70px;margin-left:30px;font-size:18px;margin-bottom:430px;" readonly>
</textarea>
<div style="width:350px;padding:25px;margin:25px;margin-left:713px;margin-top:-450px;margin-bottom:300px">
<h4>Keterangan:</h4>
<h4>- Untuk probabilitas di atas 50%, maka berita adalah hoax</h4>
<h4>- Untuk probabilitas kurang dari atau sama dengan 50%, maka berita tersebut adalah bukan hoax</h4>
</div>
{% endblock %}
{% block javascript %}
<script>
	var func = function(param){
		$.ajax({
			method: "POST",
			url: '{% url "hoax:main" %}',
			data: { paramm:param },
			dataType: 'json',
			success : function(response) {
				if ($('#res').val() != '') {
					$('#res').val('');
					$('#res').val(response.hasil);
				}
				else {
					$('#res').val(response.hasil);
				}
			},
			error : function(error) {
				console.log(error);
				alert("Mohon dicoba lagi");
			}
		})
	};
	$("#but").button().click(function (event) {
		var value = $("#temp").val();
		func(value);
		$("#res").val('Mohon Tunggu...');
		event.preventDefault();
	});
</script>
{% endblock %}

hoaxdetector/templates/hoaxdetect/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Spam Recognizer AI">
    <meta name="author" content="Intelligent Group">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title> 
        {% block title %} Hoax Detector oleh DW-IR{% endblock %}
    </title>
</head>
<body style="background-image:url(https://backgroundcheckall.com/wp-content/uploads/2017/12/bootstrap-background-7.jpg);
             background-repeat:no-repeat;background-size:1600px">
    <content>
        {% block content %}
                <!-- content goes here -->
        {% endblock %}
    </content>
   <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block javascript %}
   {% endblock %}
</body>
<footer class="section footer-classic context-dark bg-image" style="background: #2d3333;margin-top:50px;">
        <div class="container">
          <div class="row row-30">
            <div class="col-md-4 col-xl-5">
              <div class="pr-xl-4"><a class="brand"><img class="brand-logo-light" src="" alt="" width="140" height="37" srcset=""></a>
                <p>Kami adalah kedua orang anak bangsa yang mengembangkan aplikasi hoax detector, yang diharapkan mampu untuk
				membantu Masyarakat Indonesia dalam mengenali berita yang merupakan hoax dan yang bukan hoax.</p>
                <!-- Rights-->
                <p class="rights"><span>© Hak Cipta DW-IR </span><span class="copyright-year">2018</span><span>. </span></p>
              </div>
            </div>
            <div class="col-md-4">
              <h5>Kontak</h5>
              <dl class="contact-list">
                <dt>Alamat:</dt>
                <dd>Fakultas Ilmu Komputer, Universitas Indonesia, Jawa Barat.</dd>
              </dl>
              <dl class="contact-list">
                <dt>Email:</dt>
                <dd>WD4IR@gmail.com</dd>
              </dl>
            </div>
            <div class="col-md-4 col-xl-3" style="margin-top:10px">
			<dl class="contact-list">
				<dt>Nama Anggota (Kontributor):</dt>
			</dl>
              <ul class="nav-list">
                <li>Kerenza Doxolodeo - 1606881670</li>
                <li>Winston Chandra - 1606831294</li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
</footer>
<style>
.context-dark, .bg-gray-dark, .bg-primary {
    color: rgba(200, 255, 255, 0.8);
}

.footer-classic a, .footer-classic a:focus, .footer-classic a:active {
    color: #ffffff;
}
.nav-list li {
    padding-top: 5px;
    padding-bottom: 5px;
}

.nav-list li a:hover:before {
    margin-left: 0;
    opacity: 1;
    visibility: visible;
}

ul, ol {
    list-style: none;
    padding: 0;
    margin: 0;
}

.social-inner {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    padding: 23px;
    font: 900 13px/1 "Lato", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.5);
}
.social-container .col {
    border: 1px solid rgba(255, 255, 255, 0.1);
}
.nav-list li a:before {
    content: "\f14f";
    font: 400 21px/1 "Material Design Icons";
    color: #4d6dff;
    display: inline-block;
    vertical-align: baseline;
    margin-left: -28px;
    margin-right: 7px;
    opacity: 0;
    visibility: hidden;
    transition: .22s ease;
}
</style>
</html>